### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by vin-fandemand** [ApolloVM/apollovm_dart#2]
I get the following when I run Apollovm in Chrome. Is there any additional setup I need to do to make it work on web or is web simply not supported ?
```
Unhandled exception:                                                    
Unsupported operation: Undetermined Nullability                         
#0      ProgramCompiler._emitFutureOrType (package:dev_compiler/src/kernel/compiler.dart:2894:7)
#1      ProgramCompiler._normalizeFutureOr (package:dev_compiler/src/kernel/compiler.dart:2763:12)
#2      ProgramCompiler.visitFutureOrType (package:dev_compiler/src/kernel/compiler.dart:2776:7)
#3      FutureOrType.accept (package:kernel/ast.dart:11126:42)          
#4      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:2692:54)
#5      ProgramCompiler._emitTypeNames (package:dev_compiler/src/kernel/compiler.dart:3087:56)
#6      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:2976:24)
#7      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:2648:19)
#8      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:5971:12)
#9      FunctionExpression.accept (package:kernel/ast.dart:8099:44)     
#10     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)
#11     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:5413:11)
#12     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:4721:16)
#13     ProgramCompiler.visitInstanceInvocation (package:dev_compiler/src/kernel/compiler.dart:4641:12)
#14     InstanceInvocation.accept (package:kernel/ast.dart:5178:44)     
#15     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)
#16     ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:4720:22)
#17     ProgramCompiler.visitInstanceInvocation (package:dev_compiler/src/kernel/compiler.dart:4641:12)
#18     InstanceInvocation.accept (package:kernel/ast.dart:5178:44)     
#19     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)
#20     ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4235:38)
#21     ReturnStatement.accept (package:kernel/ast.dart:9497:43)        
#22     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3611:20)
#23     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3644:18)
#24     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3415:17)
#25     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2266:25)
#26     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3449:18)
#27     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3411:17)
#28     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3228:11)
#29     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:2628:14)
#30     MappedIterator.moveNext (dart:_internal/iterable.dart:390:20)   
#31     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#32     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#33     new List.of (dart:core-patch/array_patch.dart:50:28)            
#34     Iterable.toList (dart:core/iterable.dart:366:12)                
#35     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:2594:10)
#36     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:542:7)
#37     List.forEach (dart:core-patch/growable_array.dart)              
#38     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:401:15)
#39     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
<asynchronous suspension>                                               
#40     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:32)
<asynchronous suspension>                                               
#41     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:549:9)
<asynchronous suspension>                                               
#42     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1119:11)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.                                  
```

**Comment by gmpassos** [comment]
Can you put a sample project at GitHub showing this error? 

It seems a compiler error, but you didn't provide any code to analyze. 

Regards

**Comment by vin-fandemand** [comment]
It compiles when I remove ApolloVM from dependencies in pubspec.

**Comment by gmpassos** [comment]
Dart version?

**Comment by vin-fandemand** [comment]
Dart version 2.13.3
Flutter 2.2.1 stable

I also have code formatted using Dart's formatting as a string passed as codeunits source. But the petit parser keeps throwing 'end of input expected'. Is there anything that I shoud know when using string for code source?
My apologies, I have been trying to figure this out for 2 days and it has been quite frustrating.

**Comment by gmpassos** [comment]
I have tested it with a web project and it's working very well!

I have created a web example at:
https://github.com/ApolloVM/apollovm_web_example

You can try the live example at:
https://apollovm.github.io/apollovm_web_example/www/

**Comment by vin-fandemand** [comment]
I see what you did. I am using Flutter.

**Comment by gmpassos** [comment]
Please, create a simple Flutter project showing the issue and put it on GitHub. Regards

**Comment by vin-fandemand** [comment]
[https://github.com/vin-fandemand/testapollovm](https://github.com/vin-fandemand/testapollovm)

check this out.. same error...

**Comment by gmpassos** [comment]
Here it's running perfectly:

![image](https://user-images.githubusercontent.com/6723954/141212483-24b85d8b-bc61-48e7-a6c9-cc307798797a.png)

**Comment by vin-fandemand** [comment]
Can you please tell me the version of dart and flutter you are using?

**Comment by gmpassos** [comment]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (4 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by gmpassos** [comment]
I have upgraded Flutter:

![image](https://user-images.githubusercontent.com/6723954/141226209-dc5be037-fc26-423a-8af3-5fa684fa8bd7.png)

**Comment by gmpassos** [comment]
I recommend to see `flutter clean`
 and `dart pub cache clean`
